kind: pipeline
name: first-deploy
type: docker

steps:
  - name: test
    image: golang
    commands:
    - go get
    - go test
    environment:
      MESSAGE: "hello world"
    when:
      event:
        - push
