kind: pipeline
name: first-deploy

type: kubernetes

platform:
  os: linux
  arch: amd64

trigger:
  branch:
    - main
  event:
    - pull_request

steps:
  - name: testes
    pull: if-not-exists
    image: 289208114389.dkr.ecr.us-east-1.amazonaws.com/golang:alpine
    commands:
    - apk add -U --no-cache curl ca-certificates git make build-base
    - go test
    environment:
      MESSAGE: "hello world"
    when:
      event:
        - push

  # - name: sonarcloud
  #   pull: if-not-exists
  #   image: 289208114389.dkr.ecr.us-east-1.amazonaws.com/sonarsource/sonar-scanner-cli
  #   commands:
  #     - sonar-scanner -Dproject.settings=.sonarcloud.properties -Dsonar.login=$SONAR_LOGIN -Dsonar.qualitygate.wait=true
  #   environment:
  #     SONAR_PROJECT_BASE_DIR: /
  #     SONAR_LOGIN:
  #       from_secret: SONAR_LOGIN

